#!/bin/bash

echo "Branch Cleanup Plan for phaserBeam repository"
echo "============================================="
echo ""
echo "The following branches can be safely deleted as they have been merged:"
echo "- terragon/improve-marching-squares-rendering (PR #4, #5, #6 - MERGED)"
echo "- terragon/simplest-implementation (MERGED to main)"
echo ""
echo "The following branches are associated with closed PRs and can likely be deleted:"
echo "- terragon/fix-contour-rendering-bugs (PR #3 - CLOSED)"
echo "- terragon/resize-beam-profile-to-fit-window (PR #2 - CLOSED)" 
echo "- terragon/demo-interface-beam-profile (PR #1 - CLOSED)"
echo ""
echo "The following branches should be kept:"
echo "- terragon/add-annotation-mode (PR #7 - DRAFT, contains work in progress)"
echo "- feat/debug-visualization-mode (PR #8 - OPEN, current feature branch)"
echo "- terragon/last-good-with-advanced-control (backup branch, may be useful reference)"
echo ""
echo "To delete merged branches:"
echo "git push origin --delete terragon/improve-marching-squares-rendering"
echo "git push origin --delete terragon/simplest-implementation"
echo ""
echo "To delete closed PR branches (after verifying they're no longer needed):"
echo "git push origin --delete terragon/fix-contour-rendering-bugs"
echo "git push origin --delete terragon/resize-beam-profile-to-fit-window"
echo "git push origin --delete terragon/demo-interface-beam-profile"
echo ""
echo "Local cleanup (after remote deletion):"
echo "git remote prune origin"
echo "git branch -d <local-branch-name> # for any local copies"